repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: trailing-whitespace
          - id: check-merge-conflict

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ['--profile', 'black', '--filter-files', --line-length=79]

    - repo: https://github.com/pycqa/pylint
      rev: v3.3.1
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            types: [python]
            args: [
                    '-rn', # Only display messages
                    '-sn', # Don't display the score
                    '--rcfile=.pylintrc', # Link to your config file
                    '--py-version=3.9',
                ]
            exclude: 'tests/'

    - repo: https://github.com/psf/black-pre-commit-mirror
      rev: 24.2.0
      hooks:
          - id: black
            args: [--line-length, '79']
            language_version: python3.12
